platform :ios, '7.0'
xcodeproj 'Woke.xcodeproj'

#pod 'StackMob'
pod 'Weibo'
pod 'Facebook-iOS-SDK'
#pod 'ASIHTTPRequest'
pod 'Reveal-iOS-SDK'
#pod 'TestFlightSDK'
#pod 'GPUImage'
pod 'NSLogger'
pod 'Parse'
pod 'AFNetworking'
pod 'AWSiOSSDK'
pod 'MagicalRecord'