platform :ios, '7.0'
xcodeproj 'Woke.xcodeproj'

pod 'Weibo'
pod 'Facebook-iOS-SDK'
pod 'Reveal-iOS-SDK'
pod 'TestFlightSDK'
pod 'GPUImage'
pod 'NSLogger'
pod 'Parse'
pod 'AFNetworking'
pod 'MagicalRecord', '~> 2.2'#, :git => 'https://github.com/magicalpanda/MagicalRecord'# , :tag =>'v2.3.0-beta.2'
pod 'Reachability'
#pod 'SFObservers'